/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteRouteImport } from './routes/logs/route'
import { Route as BotsRouteRouteImport } from './routes/bots/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as BotsIndexRouteImport } from './routes/bots/index'
import { Route as LogsWorkerWorkerIdRouteImport } from './routes/logs/worker.$workerId'
import { Route as LogsBotBotIdRouteImport } from './routes/logs/bot.$botId'

const LogsRouteRoute = LogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRouteRoute = BotsRouteRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsRouteRoute,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsRouteRoute,
} as any)
const LogsWorkerWorkerIdRoute = LogsWorkerWorkerIdRouteImport.update({
  id: '/worker/$workerId',
  path: '/worker/$workerId',
  getParentRoute: () => LogsRouteRoute,
} as any)
const LogsBotBotIdRoute = LogsBotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => LogsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/bots/': typeof BotsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/logs/bot/$botId': typeof LogsBotBotIdRoute
  '/logs/worker/$workerId': typeof LogsWorkerWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/logs/bot/$botId': typeof LogsBotBotIdRoute
  '/logs/worker/$workerId': typeof LogsWorkerWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/bots/': typeof BotsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/logs/bot/$botId': typeof LogsBotBotIdRoute
  '/logs/worker/$workerId': typeof LogsWorkerWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/logs'
    | '/bots/'
    | '/logs/'
    | '/logs/bot/$botId'
    | '/logs/worker/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bots' | '/logs' | '/logs/bot/$botId' | '/logs/worker/$workerId'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/logs'
    | '/bots/'
    | '/logs/'
    | '/logs/bot/$botId'
    | '/logs/worker/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRouteRoute: typeof BotsRouteRouteWithChildren
  LogsRouteRoute: typeof LogsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof LogsRouteRoute
    }
    '/bots/': {
      id: '/bots/'
      path: '/'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof BotsRouteRoute
    }
    '/logs/worker/$workerId': {
      id: '/logs/worker/$workerId'
      path: '/worker/$workerId'
      fullPath: '/logs/worker/$workerId'
      preLoaderRoute: typeof LogsWorkerWorkerIdRouteImport
      parentRoute: typeof LogsRouteRoute
    }
    '/logs/bot/$botId': {
      id: '/logs/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/logs/bot/$botId'
      preLoaderRoute: typeof LogsBotBotIdRouteImport
      parentRoute: typeof LogsRouteRoute
    }
  }
}

interface BotsRouteRouteChildren {
  BotsIndexRoute: typeof BotsIndexRoute
}

const BotsRouteRouteChildren: BotsRouteRouteChildren = {
  BotsIndexRoute: BotsIndexRoute,
}

const BotsRouteRouteWithChildren = BotsRouteRoute._addFileChildren(
  BotsRouteRouteChildren,
)

interface LogsRouteRouteChildren {
  LogsIndexRoute: typeof LogsIndexRoute
  LogsBotBotIdRoute: typeof LogsBotBotIdRoute
  LogsWorkerWorkerIdRoute: typeof LogsWorkerWorkerIdRoute
}

const LogsRouteRouteChildren: LogsRouteRouteChildren = {
  LogsIndexRoute: LogsIndexRoute,
  LogsBotBotIdRoute: LogsBotBotIdRoute,
  LogsWorkerWorkerIdRoute: LogsWorkerWorkerIdRoute,
}

const LogsRouteRouteWithChildren = LogsRouteRoute._addFileChildren(
  LogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRouteRoute: BotsRouteRouteWithChildren,
  LogsRouteRoute: LogsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
