/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteRouteImport } from './routes/logs/route'
import { Route as BotsRouteRouteImport } from './routes/bots/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsWorkerIdRouteImport } from './routes/logs/$workerId'
import { Route as LogsBotIdRouteImport } from './routes/logs/$botId'

const LogsRouteRoute = LogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRouteRoute = BotsRouteRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsWorkerIdRoute = LogsWorkerIdRouteImport.update({
  id: '/$workerId',
  path: '/$workerId',
  getParentRoute: () => LogsRouteRoute,
} as any)
const LogsBotIdRoute = LogsBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => LogsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteRoute
  '/logs': typeof LogsRouteRouteWithChildren
  '/logs/$botId': typeof LogsBotIdRoute
  '/logs/$workerId': typeof LogsWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteRoute
  '/logs': typeof LogsRouteRouteWithChildren
  '/logs/$botId': typeof LogsBotIdRoute
  '/logs/$workerId': typeof LogsWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteRoute
  '/logs': typeof LogsRouteRouteWithChildren
  '/logs/$botId': typeof LogsBotIdRoute
  '/logs/$workerId': typeof LogsWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bots' | '/logs' | '/logs/$botId' | '/logs/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bots' | '/logs' | '/logs/$botId' | '/logs/$workerId'
  id: '__root__' | '/' | '/bots' | '/logs' | '/logs/$botId' | '/logs/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRouteRoute: typeof BotsRouteRoute
  LogsRouteRoute: typeof LogsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$workerId': {
      id: '/logs/$workerId'
      path: '/$workerId'
      fullPath: '/logs/$workerId'
      preLoaderRoute: typeof LogsWorkerIdRouteImport
      parentRoute: typeof LogsRouteRoute
    }
    '/logs/$botId': {
      id: '/logs/$botId'
      path: '/$botId'
      fullPath: '/logs/$botId'
      preLoaderRoute: typeof LogsBotIdRouteImport
      parentRoute: typeof LogsRouteRoute
    }
  }
}

interface LogsRouteRouteChildren {
  LogsBotIdRoute: typeof LogsBotIdRoute
  LogsWorkerIdRoute: typeof LogsWorkerIdRoute
}

const LogsRouteRouteChildren: LogsRouteRouteChildren = {
  LogsBotIdRoute: LogsBotIdRoute,
  LogsWorkerIdRoute: LogsWorkerIdRoute,
}

const LogsRouteRouteWithChildren = LogsRouteRoute._addFileChildren(
  LogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRouteRoute: BotsRouteRoute,
  LogsRouteRoute: LogsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
